import { describe, it, expect } from "vitest";
import { createSqliteTable } from "./createSqliteTable";

describe("createSqliteTable", () => {
  it("should create table from schema", async () => {
    const table = createSqliteTable({
      namespace: "test",
      name: "users",
      keyTupleSchema: { x: "uint32", y: "uint32" },
      valueSchema: { name: "string", addr: "address" },
    });

    expect(table).toMatchInlineSnapshot(`
      {
        "metaColumnNames": [
          "__lastUpdatedBlockNumber",
          "__isDeleted",
        ],
        "table": SQLiteTable {
          "__isDeleted": SQLiteBoolean {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": false,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primaryKey": false,
            },
            "default": false,
            "hasDefault": true,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "__lastUpdatedBlockNumber": SQLiteBigInt {
            "config": {
              "default": 0n,
              "hasDefault": true,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primaryKey": false,
            },
            "default": 0n,
            "hasDefault": true,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "addr": SQLiteText {
            "config": {
              "default": "0x0000000000000000000000000000000000000000",
              "enumValues": [],
              "hasDefault": true,
              "length": undefined,
              "name": "addr",
              "notNull": true,
              "primaryKey": false,
            },
            "default": "0x0000000000000000000000000000000000000000",
            "enumValues": [],
            "hasDefault": true,
            "length": undefined,
            "name": "addr",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "name": SQLiteText {
            "config": {
              "default": "",
              "enumValues": [],
              "hasDefault": true,
              "length": undefined,
              "name": "name",
              "notNull": true,
              "primaryKey": false,
            },
            "default": "",
            "enumValues": [],
            "hasDefault": true,
            "length": undefined,
            "name": "name",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "x": SQLiteInteger {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": 0,
              "hasDefault": true,
              "name": "x",
              "notNull": true,
              "primaryKey": true,
            },
            "default": 0,
            "hasDefault": true,
            "name": "x",
            "notNull": true,
            "primary": true,
            "table": [Circular],
          },
          "y": SQLiteInteger {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": 0,
              "hasDefault": true,
              "name": "y",
              "notNull": true,
              "primaryKey": true,
            },
            "default": 0,
            "hasDefault": true,
            "name": "y",
            "notNull": true,
            "primary": true,
            "table": [Circular],
          },
          Symbol(drizzle:Name): "test:users",
          Symbol(drizzle:OriginalName): "test:users",
          Symbol(drizzle:Schema): undefined,
          Symbol(drizzle:Columns): {
            "__isDeleted": SQLiteBoolean {
              "autoIncrement": false,
              "config": {
                "autoIncrement": false,
                "default": false,
                "hasDefault": true,
                "mode": "boolean",
                "name": "__isDeleted",
                "notNull": true,
                "primaryKey": false,
              },
              "default": false,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "__lastUpdatedBlockNumber": SQLiteBigInt {
              "config": {
                "default": 0n,
                "hasDefault": true,
                "name": "__lastUpdatedBlockNumber",
                "notNull": true,
                "primaryKey": false,
              },
              "default": 0n,
              "hasDefault": true,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "addr": SQLiteText {
              "config": {
                "default": "0x0000000000000000000000000000000000000000",
                "enumValues": [],
                "hasDefault": true,
                "length": undefined,
                "name": "addr",
                "notNull": true,
                "primaryKey": false,
              },
              "default": "0x0000000000000000000000000000000000000000",
              "enumValues": [],
              "hasDefault": true,
              "length": undefined,
              "name": "addr",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "name": SQLiteText {
              "config": {
                "default": "",
                "enumValues": [],
                "hasDefault": true,
                "length": undefined,
                "name": "name",
                "notNull": true,
                "primaryKey": false,
              },
              "default": "",
              "enumValues": [],
              "hasDefault": true,
              "length": undefined,
              "name": "name",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "x": SQLiteInteger {
              "autoIncrement": false,
              "config": {
                "autoIncrement": false,
                "default": 0,
                "hasDefault": true,
                "name": "x",
                "notNull": true,
                "primaryKey": true,
              },
              "default": 0,
              "hasDefault": true,
              "name": "x",
              "notNull": true,
              "primary": true,
              "table": [Circular],
            },
            "y": SQLiteInteger {
              "autoIncrement": false,
              "config": {
                "autoIncrement": false,
                "default": 0,
                "hasDefault": true,
                "name": "y",
                "notNull": true,
                "primaryKey": true,
              },
              "default": 0,
              "hasDefault": true,
              "name": "y",
              "notNull": true,
              "primary": true,
              "table": [Circular],
            },
          },
          Symbol(drizzle:BaseName): "test:users",
          Symbol(drizzle:IsAlias): false,
          Symbol(drizzle:ExtraConfigBuilder): undefined,
          Symbol(drizzle:IsDrizzleTable): true,
          Symbol(drizzle:SQLiteInlineForeignKeys): [],
        },
        "tableName": "test:users",
      }
    `);
  });

  it("can create a singleton table", async () => {
    const table = createSqliteTable({
      namespace: "test",
      name: "users",
      keyTupleSchema: {},
      valueSchema: { addrs: "address[]" },
    });

    expect(table).toMatchInlineSnapshot(`
      {
        "metaColumnNames": [
          "__lastUpdatedBlockNumber",
          "__isDeleted",
          "__singleton",
        ],
        "table": SQLiteTable {
          "__isDeleted": SQLiteBoolean {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": false,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primaryKey": false,
            },
            "default": false,
            "hasDefault": true,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "__lastUpdatedBlockNumber": SQLiteBigInt {
            "config": {
              "default": 0n,
              "hasDefault": true,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primaryKey": false,
            },
            "default": 0n,
            "hasDefault": true,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "__singleton": SQLiteBoolean {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": true,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__singleton",
              "notNull": true,
              "primaryKey": true,
            },
            "default": true,
            "hasDefault": true,
            "mode": "boolean",
            "name": "__singleton",
            "notNull": true,
            "primary": true,
            "table": [Circular],
          },
          "addrs": SQLiteCustomColumn {
            "config": {
              "customTypeParams": {
                "dataType": [Function],
                "fromDriver": [Function],
                "toDriver": [Function],
              },
              "default": "{\\"json\\":[]}",
              "fieldConfig": undefined,
              "hasDefault": true,
              "name": "addrs",
              "notNull": true,
              "primaryKey": false,
            },
            "default": "{\\"json\\":[]}",
            "hasDefault": true,
            "mapFrom": [Function],
            "mapTo": [Function],
            "name": "addrs",
            "notNull": true,
            "primary": false,
            "sqlName": "text",
            "table": [Circular],
          },
          Symbol(drizzle:Name): "test:users",
          Symbol(drizzle:OriginalName): "test:users",
          Symbol(drizzle:Schema): undefined,
          Symbol(drizzle:Columns): {
            "__isDeleted": SQLiteBoolean {
              "autoIncrement": false,
              "config": {
                "autoIncrement": false,
                "default": false,
                "hasDefault": true,
                "mode": "boolean",
                "name": "__isDeleted",
                "notNull": true,
                "primaryKey": false,
              },
              "default": false,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "__lastUpdatedBlockNumber": SQLiteBigInt {
              "config": {
                "default": 0n,
                "hasDefault": true,
                "name": "__lastUpdatedBlockNumber",
                "notNull": true,
                "primaryKey": false,
              },
              "default": 0n,
              "hasDefault": true,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primary": false,
              "table": [Circular],
            },
            "__singleton": SQLiteBoolean {
              "autoIncrement": false,
              "config": {
                "autoIncrement": false,
                "default": true,
                "hasDefault": true,
                "mode": "boolean",
                "name": "__singleton",
                "notNull": true,
                "primaryKey": true,
              },
              "default": true,
              "hasDefault": true,
              "mode": "boolean",
              "name": "__singleton",
              "notNull": true,
              "primary": true,
              "table": [Circular],
            },
            "addrs": SQLiteCustomColumn {
              "config": {
                "customTypeParams": {
                  "dataType": [Function],
                  "fromDriver": [Function],
                  "toDriver": [Function],
                },
                "default": "{\\"json\\":[]}",
                "fieldConfig": undefined,
                "hasDefault": true,
                "name": "addrs",
                "notNull": true,
                "primaryKey": false,
              },
              "default": "{\\"json\\":[]}",
              "hasDefault": true,
              "mapFrom": [Function],
              "mapTo": [Function],
              "name": "addrs",
              "notNull": true,
              "primary": false,
              "sqlName": "text",
              "table": [Circular],
            },
          },
          Symbol(drizzle:BaseName): "test:users",
          Symbol(drizzle:IsAlias): false,
          Symbol(drizzle:ExtraConfigBuilder): undefined,
          Symbol(drizzle:IsDrizzleTable): true,
          Symbol(drizzle:SQLiteInlineForeignKeys): [],
        },
        "tableName": "test:users",
      }
    `);
  });
});
