name: Setup
description: Common setup steps used by our workflows
runs:
  using: composite
  steps:
    - name: Setup prerequisites
      uses: ./.github/actions/setup-prerequisites

    # pnpm no longer runs this before the actual install (https://github.com/pnpm/pnpm/issues/3760)
    # but we need to create some placeholder files like bins so that the install step can find them and put references to them in the right spot
    # this resolves some chicken-and-egg problems with using workspace bins before they're created (install -> build -> install)
    - name: Run prepare scripts
      shell: bash
      run: pnpm recursive run prepare

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    # Workaround for parallel building with forge:
    # https://github.com/foundry-rs/foundry/issues/4736
    - name: Setup forge
      shell: bash
      working-directory: packages/schema-type
      run: forge build
