name: Setup
description: Common setup steps used by our workflows
inputs:
 node-version:
    description: 'Node.js version to install'
    required: true
    default: 18
runs:
  using: composite
  steps:
    - name: Setup prerequisites
      uses: ./.github/actions/setup-prerequisites
      with:
          node-version: ${{ inputs.node-version }}

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    # Workaround for parallel building with forge:
    # https://github.com/foundry-rs/foundry/issues/4736
    - name: Setup forge
      shell: bash
      working-directory: packages/schema-type
      run: forge build