name: Setup
description: Common setup steps used by our workflows
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.x

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
      # TODO update when "max fee per gas" issue is fixed for latest nightly
        version: nightly-87bc53fc6c874bd4c92d97ed180b949e3a36d78c

    - name: Setup protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ github.token }}

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    # Workaround for parallel building with forge:
    # https://github.com/foundry-rs/foundry/issues/4736
    - name: Setup forge
      shell: bash
      working-directory: packages/schema-type
      run: forge build

    - name: Cache turbo build
      uses: actions/cache@v3
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Build
      shell: bash
      run: pnpm turbo run build --cache-dir=.turbo --concurrency 10

    - name: Outdated files, run `pnpm build` and commit them
      uses: ./.github/actions/require-empty-diff
