---
chains:
  - name: "lattice-testnet"
    id: "4242"
    rpc:
      http: "https://miner.testnet-chain.linfra.xyz/"
      ws: "wss://miner.testnet-chain.linfra.xyz/ws"
db:
  dsn: "postgresql://localhost:5433/mode_ephemeral?sslmode=disable&replication=database"
  dsnGorm: "host=localhost dbname=mode_ephemeral port=5433 sslmode=disable"
  wipe: true
sync:
  enabled: true
  startBlock: 14522920
  blockBatchCount: 100
ql:
  port: 50091
metrics:
  port: 6060
