version: "3.8"
services:
  db:
    image: ghcr.io/latticexyz/postgres-wal-logical:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=mode_ephemeral
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  mode:
    build:
      context: .
      dockerfile: Dockerfile.mode
    ports:
      - 50091:50091
      - 50092:50092
      - 6060:6060
    depends_on:
      db:
        condition: service_healthy
    command: ./service/mode --config ./service/config.mode-docker.yaml
    restart: on-failure
