version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=mode_ephemeral
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  mode:
    build:
      context: .
      dockerfile: Dockerfile.mode
    ports:
      - 50091:50091
    depends_on:
      db:
        condition: service_healthy
    command: ./service/mode --config ./service/config.mode-docker.yaml
    network_mode: host
    restart: on-failure
