import { editor } from "monaco-editor/esm/vs/editor/editor.api";

export const monacoOptions: editor.IStandaloneEditorConstructionOptions = {
  fontSize: 14,
  fontWeight: "normal",
  wordWrap: "off",
  lineNumbers: "off",
  lineNumbersMinChars: 0,
  overviewRulerLanes: 0,
  overviewRulerBorder: false,
  hideCursorInOverviewRuler: true,
  lineDecorationsWidth: 0,
  glyphMargin: false,
  folding: false,
  scrollBeyondLastColumn: 0,
  scrollbar: {
    horizontal: "hidden",
    vertical: "hidden",
    alwaysConsumeMouseWheel: false,
    handleMouseWheel: false,
  },
  find: {
    addExtraSpaceOnTop: false,
    autoFindInSelection: "never",
    seedSearchStringFromSelection: "never",
  },
  minimap: { enabled: false },
  wordBasedSuggestions: "off",
  links: false,
  occurrencesHighlight: "off",
  cursorStyle: "line-thin",
  renderLineHighlight: "none",
  contextmenu: false,
  roundedSelection: false,
  hover: {
    delay: 100,
  },
  acceptSuggestionOnEnter: "on",
  automaticLayout: true,
  fixedOverflowWidgets: true,
};
