/* Autogenerated file. Do not edit manually. */

import {
  defineComponent,
  Type as RecsType,
  type World,
} from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: defineComponent(
      world,
      {
        value: RecsType.Number,
      },
      {
        id: "0x00000000000000000000000000000000436f756e746572000000000000000000",
        metadata: {
          componentName: "Counter",
          tableName: ":Counter",
          keySchema: {},
          valueSchema: { value: "uint32" },
        },
      } as const
    ),
  };
}
