// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("TemplateContent")));
bytes32 constant TemplateContentTableId = _tableId;

library TemplateContent {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](1);
    _fieldNames[0] = "value";
    return ("TemplateContent", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get value */
  function get(bytes32 templateId, bytes32 tableId) internal view returns (bytes memory value) {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 0);
    return (bytes(_blob));
  }

  /** Get value (using the specified store) */
  function get(IStore _store, bytes32 templateId, bytes32 tableId) internal view returns (bytes memory value) {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 0);
    return (bytes(_blob));
  }

  /** Set value */
  function set(bytes32 templateId, bytes32 tableId, bytes memory value) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    StoreSwitch.setField(_tableId, _primaryKeys, 0, bytes((value)));
  }

  /** Set value (using the specified store) */
  function set(IStore _store, bytes32 templateId, bytes32 tableId, bytes memory value) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    _store.setField(_tableId, _primaryKeys, 0, bytes((value)));
  }

  /** Push a slice to value */
  function push(bytes32 templateId, bytes32 tableId, bytes memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    StoreSwitch.pushToField(_tableId, _primaryKeys, 0, bytes((_slice)));
  }

  /** Push a slice to value (using the specified store) */
  function push(IStore _store, bytes32 templateId, bytes32 tableId, bytes memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    _store.pushToField(_tableId, _primaryKeys, 0, bytes((_slice)));
  }

  /** Pop a slice from value */
  function pop(bytes32 templateId, bytes32 tableId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    StoreSwitch.popFromField(_tableId, _primaryKeys, 0, 1);
  }

  /** Pop a slice from value (using the specified store) */
  function pop(IStore _store, bytes32 templateId, bytes32 tableId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    _store.popFromField(_tableId, _primaryKeys, 0, 1);
  }

  /** Update a slice of value at `_index` */
  function update(bytes32 templateId, bytes32 tableId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    StoreSwitch.updateInField(_tableId, _primaryKeys, 0, _index * 1, bytes((_slice)));
  }

  /** Update a slice of value (using the specified store) at `_index` */
  function update(IStore _store, bytes32 templateId, bytes32 tableId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    _store.updateInField(_tableId, _primaryKeys, 0, _index * 1, bytes((_slice)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(bytes memory value) internal view returns (bytes memory) {
    uint16[] memory _counters = new uint16[](1);
    _counters[0] = uint16(bytes(value).length);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(_encodedLengths.unwrap(), bytes((value)));
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 templateId, bytes32 tableId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    StoreSwitch.deleteRecord(_tableId, _primaryKeys);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 templateId, bytes32 tableId) internal {
    bytes32[] memory _primaryKeys = new bytes32[](2);
    _primaryKeys[0] = bytes32((templateId));
    _primaryKeys[1] = bytes32((tableId));

    _store.deleteRecord(_tableId, _primaryKeys);
  }
}
