[profile.default]
solc_version = "0.8.13"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
verbosity = 2
allow_paths = ["../../node_modules", "../solecs"]
src = "src"
out = "out"

[fmt]
tab_width = 2
bracket_spacing = true
ignore = ['**/codegen/**/*.sol']
