/* Autogenerated file. Do not edit manually. */

interface ConfigType {
  Statics?: {
    v1: bigint;
    v2: number;
    v3: string;
    v4: string;
    v5: boolean;
    v6: "E1" | "E2" | "E3";
    v7: "E1";
  };
  Dynamics?: {
    staticB32: bigint[];
    staticI32: number[];
    staticU128: bigint[];
    staticAddrs: string[];
    staticBools: boolean[];
    u64: bigint[];
    str: string;
    b: string;
  };
  Singleton?: { v1: bigint; v2: number[]; v3: number[]; v4: number[] };
  Ephemeral?: { value: bigint };
  Counter?: { value: bigint };
}

export interface TemplateConfig {
  templates: Record<string, ConfigType>;
}

export function templateConfig(config: TemplateConfig) {
  return config;
}
