// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BSystem } from "../../BSystem.sol";
import { ASystemThing } from "../../../a/ASystemTypes.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type BSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "b", name: "BSystem" }))
BSystemType constant bSystem = BSystemType.wrap(0x737962000000000000000000000000004253797374656d000000000000000000);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title BSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library BSystemLib {
  error BSystemLib_CallingFromRootSystem();

  function setValueInA(BSystemType self, ASystemThing memory thing) internal {
    return CallWrapper(self.toResourceId(), address(0)).setValueInA(thing);
  }

  function getValueFromA(BSystemType self) internal view returns (uint256) {
    return CallWrapper(self.toResourceId(), address(0)).getValueFromA();
  }

  function setValueInA(CallWrapper memory self, ASystemThing memory thing) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeWithSelector(bytes4(keccak256("BSystem.setValueInA")), (thing));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getValueFromA(CallWrapper memory self) internal view returns (uint256) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert BSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeWithSelector(bytes4(keccak256("BSystem.getValueFromA")));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    return abi.decode(result, (uint256));
  }

  function setValueInA(RootCallWrapper memory self, ASystemThing memory thing) internal {
    bytes memory systemCall = abi.encodeWithSelector(bytes4(keccak256("BSystem.setValueInA")), (thing));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getValueFromA(RootCallWrapper memory self) internal view returns (uint256) {
    bytes memory systemCall = abi.encodeWithSelector(bytes4(keccak256("BSystem.getValueFromA")));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    return abi.decode(result, (uint256));
  }

  function callFrom(BSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(BSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(BSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(BSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(BSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (BSystemType) {
    return BSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(BSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

using BSystemLib for BSystemType global;
using BSystemLib for CallWrapper global;
using BSystemLib for RootCallWrapper global;
