// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ASystemThing } from "../../namespaces/a/ASystemTypes.sol";

/**
 * @title IASystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IASystem {
  function a__setValue(ASystemThing memory value) external;

  function a__setValue(uint256 value) external;

  function a__getValue() external view returns (uint256);

  function a__getTwoValues() external view returns (uint256, uint256);

  function a__setAddress() external returns (address);
}
