import { RecsV1TableOptions } from "./types.js";

export function renderRecsV1Tables(options: RecsV1TableOptions) {
  const { tables } = options;

  return `/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ${tables
      .map(
        (table) => `
      ${table.tableName}: ${renderDefineComponent(table)},
    `
      )
      .join("")}
  }
}
`;
}

function renderDefineComponent(table: RecsV1TableOptions["tables"][number]) {
  const { namespace, fileSelector } = table.staticResourceData;
  return `
    (() => {
      const tableId = new TableId("${namespace}", "${fileSelector}");
      return defineComponent(world, {
        ${table.fields.map(({ name, recsTypeString }) => `${name}: ${recsTypeString},`).join("")}
      }, {
        metadata: { contractId: tableId.toHexString(), tableId: tableId.toString() },
      });
    })()
  `;
}
