// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Bool } from "./tables/Bool.sol";
import { TwoFields, TwoFieldsData } from "./tables/TwoFields.sol";
import { AddressArray } from "./tables/AddressArray.sol";
