[profile.default]
solc = "0.8.21"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
allow_paths= ["../../node_modules"]
src = "src"
out = "out"
bytecode_hash = "none"
extra_output_files = [
  "abi",
  "evm.bytecode"
]
