// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./../codegen/tables/Position.sol";
import { Health } from "./../codegen/tables/Health.sol";
import { Inventory } from "./../codegen/tables/Inventory.sol";
import { Score } from "./../codegen/tables/Score.sol";
import { Winner } from "./../codegen/tables/Winner.sol";
import { Terrain } from "./../codegen/tables/Terrain.sol";
