export const projects = [
  {
    name: "Biomes",
    icon: "/ecosystem/icons/biomes.png",
    bgImage: "/ecosystem/bg/everlon.png",
    url: "https://biomes.aw",
  },
  {
    name: "EVE Frontier",
    icon: "/ecosystem/icons/eve-frontier.jpg",
    bgImage: "/ecosystem/bg/eve-frontier.jpg",
    url: "https://evefrontier.com/en",
  },
  {
    name: "CafeCosmos",
    icon: "/ecosystem/icons/cafe-cosmos.png",
    bgImage: "/ecosystem/bg/cafe-cosmos.jpeg",
    url: "https://x.com/CafeCosmosHQ",
  },
  {
    name: "This Cursed Machine",
    icon: "/ecosystem/icons/thiscursedmachine.png",
    bgImage: "/ecosystem/bg/thiscursedmachine.png",
    url: "https://thiscursedmachine.fun/",
  },
  {
    name: "Battle for Blockchain",
    icon: "/ecosystem/icons/battle-blockchain.png",
    bgImage: "/ecosystem/bg/battle-blockchain.jpeg",
    url: "https://x.com/battleforblock",
  },
  {
    name: "For the Kingdom",
    icon: "/ecosystem/icons/for-kingdom.png",
    bgImage: "/ecosystem/bg/for-kingdom.jpeg",
    url: "https://x.com/4thekingdom_xyz",
  },
  {
    name: "Words3",
    icon: "/ecosystem/icons/words3.png",
    bgImage: "/ecosystem/bg/words3.png",
    url: "https://www.words3.xyz/",
  },
  {
    name: "Primodium",
    icon: "/ecosystem/icons/primodium.jpg",
    bgImage: "/ecosystem/bg/primodium.png",
    url: "https://x.com/primodiumgame",
  },
  {
    name: "Dappmon",
    icon: "/ecosystem/icons/dappmon.jpg",
    bgImage: "/ecosystem/bg/dappmon.jpeg",
    url: "dappmon.xyz",
  },
  {
    name: "Project Mirage",
    icon: "/ecosystem/icons/project-mirage.jpg",
    bgImage: "/ecosystem/bg/project-mirage.jpeg",
    url: "https://x.com/mirage_game_",
  },
  {
    name: "Yonk",
    icon: "/ecosystem/icons/yonk.png",
    bgImage: "/ecosystem/bg/yonk.png",
    url: "https://apps.apple.com/gb/app/yonk/id6478030288",
  },
  {
    name: "Dear",
    icon: "/ecosystem/icons/dear.png",
    bgImage: "/ecosystem/bg/dear.png",
    url: "https://www.dear.game/",
  },
  {
    name: "PopCraft",
    icon: "/ecosystem/icons/popcraft.jpg",
    bgImage: "/ecosystem/bg/popcraft.png",
    url: "https://x.com/PopCraftOnChain",
  },
  {
    name: "Aether Sands",
    description: "An onchain open-world survival & resource management game.",
    icon: "/ecosystem/icons/aethersands.png",
    bgImage: "/ecosystem/bg/aethersands.png",
    url: "https://x.com/aether_sands",
    mud: true,
    redstone: false,
  },
  {
    name: "Geoweb",
    description: "A public good augmented reality network.",
    icon: "/ecosystem/icons/geoweb.png",
    bgImage: "/ecosystem/bg/geoweb.png",
    url: "https://x.com/thegeoweb",
    mud: true,
    redstone: false,
  },
];
