[profile.default]
allow_paths = ["../../node_modules", "../node_modules"]
bytecode_hash = "none"
extra_output_files = [
  "abi",
  "evm.bytecode",
]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
out = "out"
solc = "0.8.21"
src = "src"
verbosity = 2
