// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "./../../WorldResourceId.sol";

/**
 * @title IAccessManagementSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAccessManagementSystem {
  function grantAccess(ResourceId resourceId, address grantee) external;

  function revokeAccess(ResourceId resourceId, address grantee) external;

  function transferOwnership(ResourceId namespaceId, address newOwner) external;
}
