// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IChatSystem
 * @notice This is an autogenerated interface that represents a MUD system.
 * @dev Users of this system are advised not to manually edit this file.
 */
interface IChatSystem {
  function sendMessage(string memory message) external;
}
