// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IIncrementSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IIncrementSystem {
  error MyCustomError();

  function increment() external returns (uint32);

  function willRevert() external;
}
