// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  error MyCustomError();

  function increment() external returns (uint32);

  function willRevert() external;
}
