// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { BytesStruct, StringStruct } from "./../../systems/structs.sol";

/**
 * @title IStructSystem
 * @notice This is an autogenerated interface that represents a MUD system.
 * @dev Users of this system are advised not to manually edit this file.
 */
interface IStructSystem {
  function staticArrayBytesStruct(BytesStruct[1] memory) external;

  function dynamicArrayBytesStruct(BytesStruct[] memory) external;

  function staticArrayStringStruct(StringStruct[1] memory) external;

  function dynamicArrayStringStruct(StringStruct[] memory) external;
}
