/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IStoreHookInterface extends utils.Interface {
  contractName: "IStoreHook";
  functions: {
    "onDeleteRecord(uint256,bytes32[])": FunctionFragment;
    "onSetField(uint256,bytes32[],uint8,bytes)": FunctionFragment;
    "onSetRecord(uint256,bytes32[],bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "onDeleteRecord",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetField",
    values: [BigNumberish, BytesLike[], BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetRecord",
    values: [BigNumberish, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "onDeleteRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onSetField", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onSetRecord",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IStoreHook extends BaseContract {
  contractName: "IStoreHook";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStoreHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    onDeleteRecord(
      table: BigNumberish,
      key: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onSetField(
      table: BigNumberish,
      key: BytesLike[],
      schemaIndex: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onSetRecord(
      table: BigNumberish,
      key: BytesLike[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  onDeleteRecord(
    table: BigNumberish,
    key: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onSetField(
    table: BigNumberish,
    key: BytesLike[],
    schemaIndex: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onSetRecord(
    table: BigNumberish,
    key: BytesLike[],
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    onDeleteRecord(
      table: BigNumberish,
      key: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    onSetField(
      table: BigNumberish,
      key: BytesLike[],
      schemaIndex: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    onSetRecord(
      table: BigNumberish,
      key: BytesLike[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    onDeleteRecord(
      table: BigNumberish,
      key: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onSetField(
      table: BigNumberish,
      key: BytesLike[],
      schemaIndex: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onSetRecord(
      table: BigNumberish,
      key: BytesLike[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onDeleteRecord(
      table: BigNumberish,
      key: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onSetField(
      table: BigNumberish,
      key: BytesLike[],
      schemaIndex: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onSetRecord(
      table: BigNumberish,
      key: BytesLike[],
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
