// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "./../WorldResourceId.sol";

interface IAccessManagementSystem {
  function grantAccess(ResourceId resourceId, address grantee) external;

  function revokeAccess(ResourceId resourceId, address grantee) external;

  function transferOwnership(bytes14 namespace, address newOwner) external;
}
