// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TodoItem, TodoItemData, TodoItemTableId } from "./tables/TodoItem.sol";
import { Owned, OwnedTableId } from "./tables/Owned.sol";
