// WARNING: this should mirror any changes to store's SchemaType
export enum ContractSchemaType {
  UINT8,
  UINT16,
  UINT24,
  UINT32,
  UINT40,
  UINT48,
  UINT56,
  UINT64,
  UINT72,
  UINT80,
  UINT88,
  UINT96,
  UINT104,
  UINT112,
  UINT120,
  UINT128,
  UINT136,
  UINT144,
  UINT152,
  UINT160,
  UINT168,
  UINT176,
  UINT184,
  UINT192,
  UINT200,
  UINT208,
  UINT216,
  UINT224,
  UINT232,
  UINT240,
  UINT248,
  UINT256,
  INT8,
  INT16,
  INT24,
  INT32,
  INT40,
  INT48,
  INT56,
  INT64,
  INT72,
  INT80,
  INT88,
  INT96,
  INT104,
  INT112,
  INT120,
  INT128,
  INT136,
  INT144,
  INT152,
  INT160,
  INT168,
  INT176,
  INT184,
  INT192,
  INT200,
  INT208,
  INT216,
  INT224,
  INT232,
  INT240,
  INT248,
  INT256,
  BYTES1,
  BYTES2,
  BYTES3,
  BYTES4,
  BYTES5,
  BYTES6,
  BYTES7,
  BYTES8,
  BYTES9,
  BYTES10,
  BYTES11,
  BYTES12,
  BYTES13,
  BYTES14,
  BYTES15,
  BYTES16,
  BYTES17,
  BYTES18,
  BYTES19,
  BYTES20,
  BYTES21,
  BYTES22,
  BYTES23,
  BYTES24,
  BYTES25,
  BYTES26,
  BYTES27,
  BYTES28,
  BYTES29,
  BYTES30,
  BYTES31,
  BYTES32,
  BOOL,
  ADDRESS,
  UINT8_ARRAY,
  UINT16_ARRAY,
  UINT24_ARRAY,
  UINT32_ARRAY,
  UINT40_ARRAY,
  UINT48_ARRAY,
  UINT56_ARRAY,
  UINT64_ARRAY,
  UINT72_ARRAY,
  UINT80_ARRAY,
  UINT88_ARRAY,
  UINT96_ARRAY,
  UINT104_ARRAY,
  UINT112_ARRAY,
  UINT120_ARRAY,
  UINT128_ARRAY,
  UINT136_ARRAY,
  UINT144_ARRAY,
  UINT152_ARRAY,
  UINT160_ARRAY,
  UINT168_ARRAY,
  UINT176_ARRAY,
  UINT184_ARRAY,
  UINT192_ARRAY,
  UINT200_ARRAY,
  UINT208_ARRAY,
  UINT216_ARRAY,
  UINT224_ARRAY,
  UINT232_ARRAY,
  UINT240_ARRAY,
  UINT248_ARRAY,
  UINT256_ARRAY,
  INT8_ARRAY,
  INT16_ARRAY,
  INT24_ARRAY,
  INT32_ARRAY,
  INT40_ARRAY,
  INT48_ARRAY,
  INT56_ARRAY,
  INT64_ARRAY,
  INT72_ARRAY,
  INT80_ARRAY,
  INT88_ARRAY,
  INT96_ARRAY,
  INT104_ARRAY,
  INT112_ARRAY,
  INT120_ARRAY,
  INT128_ARRAY,
  INT136_ARRAY,
  INT144_ARRAY,
  INT152_ARRAY,
  INT160_ARRAY,
  INT168_ARRAY,
  INT176_ARRAY,
  INT184_ARRAY,
  INT192_ARRAY,
  INT200_ARRAY,
  INT208_ARRAY,
  INT216_ARRAY,
  INT224_ARRAY,
  INT232_ARRAY,
  INT240_ARRAY,
  INT248_ARRAY,
  INT256_ARRAY,
  BYTES1_ARRAY,
  BYTES2_ARRAY,
  BYTES3_ARRAY,
  BYTES4_ARRAY,
  BYTES5_ARRAY,
  BYTES6_ARRAY,
  BYTES7_ARRAY,
  BYTES8_ARRAY,
  BYTES9_ARRAY,
  BYTES10_ARRAY,
  BYTES11_ARRAY,
  BYTES12_ARRAY,
  BYTES13_ARRAY,
  BYTES14_ARRAY,
  BYTES15_ARRAY,
  BYTES16_ARRAY,
  BYTES17_ARRAY,
  BYTES18_ARRAY,
  BYTES19_ARRAY,
  BYTES20_ARRAY,
  BYTES21_ARRAY,
  BYTES22_ARRAY,
  BYTES23_ARRAY,
  BYTES24_ARRAY,
  BYTES25_ARRAY,
  BYTES26_ARRAY,
  BYTES27_ARRAY,
  BYTES28_ARRAY,
  BYTES29_ARRAY,
  BYTES30_ARRAY,
  BYTES31_ARRAY,
  BYTES32_ARRAY,
  BOOL_ARRAY,
  ADDRESS_ARRAY,
  BYTES,
  STRING,
}

export function getStaticByteLength(schemaType: ContractSchemaType) {
  const val = schemaType.valueOf();
  if (val < 32) {
    // uint8-256
    return val + 1;
  } else if (val < 64) {
    // int8-256, offset by 32
    return val + 1 - 32;
  } else if (val < 96) {
    // bytes1-32, offset by 64
    return val + 1 - 64;
  }

  // Other static types
  if (schemaType == ContractSchemaType.BOOL) {
    return 1;
  } else if (schemaType == ContractSchemaType.ADDRESS) {
    return 20;
  }

  // Return 0 for all dynamic types
  return 0;
}

export const ContractSchemaTypeId: { [key in ContractSchemaType]: string } = {
  [ContractSchemaType.UINT8]: "uint8",
  [ContractSchemaType.UINT16]: "uint16",
  [ContractSchemaType.UINT24]: "uint24",
  [ContractSchemaType.UINT32]: "uint32",
  [ContractSchemaType.UINT40]: "uint40",
  [ContractSchemaType.UINT48]: "uint48",
  [ContractSchemaType.UINT56]: "uint56",
  [ContractSchemaType.UINT64]: "uint64",
  [ContractSchemaType.UINT72]: "uint72",
  [ContractSchemaType.UINT80]: "uint80",
  [ContractSchemaType.UINT88]: "uint88",
  [ContractSchemaType.UINT96]: "uint96",
  [ContractSchemaType.UINT104]: "uint104",
  [ContractSchemaType.UINT112]: "uint112",
  [ContractSchemaType.UINT120]: "uint120",
  [ContractSchemaType.UINT128]: "uint128",
  [ContractSchemaType.UINT136]: "uint136",
  [ContractSchemaType.UINT144]: "uint144",
  [ContractSchemaType.UINT152]: "uint152",
  [ContractSchemaType.UINT160]: "uint160",
  [ContractSchemaType.UINT168]: "uint168",
  [ContractSchemaType.UINT176]: "uint176",
  [ContractSchemaType.UINT184]: "uint184",
  [ContractSchemaType.UINT192]: "uint192",
  [ContractSchemaType.UINT200]: "uint200",
  [ContractSchemaType.UINT208]: "uint208",
  [ContractSchemaType.UINT216]: "uint216",
  [ContractSchemaType.UINT224]: "uint224",
  [ContractSchemaType.UINT232]: "uint232",
  [ContractSchemaType.UINT240]: "uint240",
  [ContractSchemaType.UINT248]: "uint248",
  [ContractSchemaType.UINT256]: "uint256",

  [ContractSchemaType.INT8]: "int8",
  [ContractSchemaType.INT16]: "int16",
  [ContractSchemaType.INT24]: "int24",
  [ContractSchemaType.INT32]: "int32",
  [ContractSchemaType.INT40]: "int40",
  [ContractSchemaType.INT48]: "int48",
  [ContractSchemaType.INT56]: "int56",
  [ContractSchemaType.INT64]: "int64",
  [ContractSchemaType.INT72]: "int72",
  [ContractSchemaType.INT80]: "int80",
  [ContractSchemaType.INT88]: "int88",
  [ContractSchemaType.INT96]: "int96",
  [ContractSchemaType.INT104]: "int104",
  [ContractSchemaType.INT112]: "int112",
  [ContractSchemaType.INT120]: "int120",
  [ContractSchemaType.INT128]: "int128",
  [ContractSchemaType.INT136]: "int136",
  [ContractSchemaType.INT144]: "int144",
  [ContractSchemaType.INT152]: "int152",
  [ContractSchemaType.INT160]: "int160",
  [ContractSchemaType.INT168]: "int168",
  [ContractSchemaType.INT176]: "int176",
  [ContractSchemaType.INT184]: "int184",
  [ContractSchemaType.INT192]: "int192",
  [ContractSchemaType.INT200]: "int200",
  [ContractSchemaType.INT208]: "int208",
  [ContractSchemaType.INT216]: "int216",
  [ContractSchemaType.INT224]: "int224",
  [ContractSchemaType.INT232]: "int232",
  [ContractSchemaType.INT240]: "int240",
  [ContractSchemaType.INT248]: "int248",
  [ContractSchemaType.INT256]: "int256",

  [ContractSchemaType.BYTES1]: "bytes1",
  [ContractSchemaType.BYTES2]: "bytes2",
  [ContractSchemaType.BYTES3]: "bytes3",
  [ContractSchemaType.BYTES4]: "bytes4",
  [ContractSchemaType.BYTES5]: "bytes5",
  [ContractSchemaType.BYTES6]: "bytes6",
  [ContractSchemaType.BYTES7]: "bytes7",
  [ContractSchemaType.BYTES8]: "bytes8",
  [ContractSchemaType.BYTES9]: "bytes9",
  [ContractSchemaType.BYTES10]: "bytes10",
  [ContractSchemaType.BYTES11]: "bytes11",
  [ContractSchemaType.BYTES12]: "bytes12",
  [ContractSchemaType.BYTES13]: "bytes13",
  [ContractSchemaType.BYTES14]: "bytes14",
  [ContractSchemaType.BYTES15]: "bytes15",
  [ContractSchemaType.BYTES16]: "bytes16",
  [ContractSchemaType.BYTES17]: "bytes17",
  [ContractSchemaType.BYTES18]: "bytes18",
  [ContractSchemaType.BYTES19]: "bytes19",
  [ContractSchemaType.BYTES20]: "bytes20",
  [ContractSchemaType.BYTES21]: "bytes21",
  [ContractSchemaType.BYTES22]: "bytes22",
  [ContractSchemaType.BYTES23]: "bytes23",
  [ContractSchemaType.BYTES24]: "bytes24",
  [ContractSchemaType.BYTES25]: "bytes25",
  [ContractSchemaType.BYTES26]: "bytes26",
  [ContractSchemaType.BYTES27]: "bytes27",
  [ContractSchemaType.BYTES28]: "bytes28",
  [ContractSchemaType.BYTES29]: "bytes29",
  [ContractSchemaType.BYTES30]: "bytes30",
  [ContractSchemaType.BYTES31]: "bytes31",
  [ContractSchemaType.BYTES32]: "bytes32",

  [ContractSchemaType.BOOL]: "bool",
  [ContractSchemaType.ADDRESS]: "address",

  [ContractSchemaType.UINT8_ARRAY]: "uint8[]",
  [ContractSchemaType.UINT16_ARRAY]: "uint16[]",
  [ContractSchemaType.UINT24_ARRAY]: "uint24[]",
  [ContractSchemaType.UINT32_ARRAY]: "uint32[]",
  [ContractSchemaType.UINT40_ARRAY]: "uint40[]",
  [ContractSchemaType.UINT48_ARRAY]: "uint48[]",
  [ContractSchemaType.UINT56_ARRAY]: "uint56[]",
  [ContractSchemaType.UINT64_ARRAY]: "uint64[]",
  [ContractSchemaType.UINT72_ARRAY]: "uint72[]",
  [ContractSchemaType.UINT80_ARRAY]: "uint80[]",
  [ContractSchemaType.UINT88_ARRAY]: "uint88[]",
  [ContractSchemaType.UINT96_ARRAY]: "uint96[]",
  [ContractSchemaType.UINT104_ARRAY]: "uint104[]",
  [ContractSchemaType.UINT112_ARRAY]: "uint112[]",
  [ContractSchemaType.UINT120_ARRAY]: "uint120[]",
  [ContractSchemaType.UINT128_ARRAY]: "uint128[]",
  [ContractSchemaType.UINT136_ARRAY]: "uint136[]",
  [ContractSchemaType.UINT144_ARRAY]: "uint144[]",
  [ContractSchemaType.UINT152_ARRAY]: "uint152[]",
  [ContractSchemaType.UINT160_ARRAY]: "uint160[]",
  [ContractSchemaType.UINT168_ARRAY]: "uint168[]",
  [ContractSchemaType.UINT176_ARRAY]: "uint176[]",
  [ContractSchemaType.UINT184_ARRAY]: "uint184[]",
  [ContractSchemaType.UINT192_ARRAY]: "uint192[]",
  [ContractSchemaType.UINT200_ARRAY]: "uint200[]",
  [ContractSchemaType.UINT208_ARRAY]: "uint208[]",
  [ContractSchemaType.UINT216_ARRAY]: "uint216[]",
  [ContractSchemaType.UINT224_ARRAY]: "uint224[]",
  [ContractSchemaType.UINT232_ARRAY]: "uint232[]",
  [ContractSchemaType.UINT240_ARRAY]: "uint240[]",
  [ContractSchemaType.UINT248_ARRAY]: "uint248[]",
  [ContractSchemaType.UINT256_ARRAY]: "uint256[]",

  [ContractSchemaType.INT8_ARRAY]: "int8[]",
  [ContractSchemaType.INT16_ARRAY]: "int16[]",
  [ContractSchemaType.INT24_ARRAY]: "int24[]",
  [ContractSchemaType.INT32_ARRAY]: "int32[]",
  [ContractSchemaType.INT40_ARRAY]: "int40[]",
  [ContractSchemaType.INT48_ARRAY]: "int48[]",
  [ContractSchemaType.INT56_ARRAY]: "int56[]",
  [ContractSchemaType.INT64_ARRAY]: "int64[]",
  [ContractSchemaType.INT72_ARRAY]: "int72[]",
  [ContractSchemaType.INT80_ARRAY]: "int80[]",
  [ContractSchemaType.INT88_ARRAY]: "int88[]",
  [ContractSchemaType.INT96_ARRAY]: "int96[]",
  [ContractSchemaType.INT104_ARRAY]: "int104[]",
  [ContractSchemaType.INT112_ARRAY]: "int112[]",
  [ContractSchemaType.INT120_ARRAY]: "int120[]",
  [ContractSchemaType.INT128_ARRAY]: "int128[]",
  [ContractSchemaType.INT136_ARRAY]: "int136[]",
  [ContractSchemaType.INT144_ARRAY]: "int144[]",
  [ContractSchemaType.INT152_ARRAY]: "int152[]",
  [ContractSchemaType.INT160_ARRAY]: "int160[]",
  [ContractSchemaType.INT168_ARRAY]: "int168[]",
  [ContractSchemaType.INT176_ARRAY]: "int176[]",
  [ContractSchemaType.INT184_ARRAY]: "int184[]",
  [ContractSchemaType.INT192_ARRAY]: "int192[]",
  [ContractSchemaType.INT200_ARRAY]: "int200[]",
  [ContractSchemaType.INT208_ARRAY]: "int208[]",
  [ContractSchemaType.INT216_ARRAY]: "int216[]",
  [ContractSchemaType.INT224_ARRAY]: "int224[]",
  [ContractSchemaType.INT232_ARRAY]: "int232[]",
  [ContractSchemaType.INT240_ARRAY]: "int240[]",
  [ContractSchemaType.INT248_ARRAY]: "int248[]",
  [ContractSchemaType.INT256_ARRAY]: "int256[]",

  [ContractSchemaType.BYTES1_ARRAY]: "bytes1[]",
  [ContractSchemaType.BYTES2_ARRAY]: "bytes2[]",
  [ContractSchemaType.BYTES3_ARRAY]: "bytes3[]",
  [ContractSchemaType.BYTES4_ARRAY]: "bytes4[]",
  [ContractSchemaType.BYTES5_ARRAY]: "bytes5[]",
  [ContractSchemaType.BYTES6_ARRAY]: "bytes6[]",
  [ContractSchemaType.BYTES7_ARRAY]: "bytes7[]",
  [ContractSchemaType.BYTES8_ARRAY]: "bytes8[]",
  [ContractSchemaType.BYTES9_ARRAY]: "bytes9[]",
  [ContractSchemaType.BYTES10_ARRAY]: "bytes10[]",
  [ContractSchemaType.BYTES11_ARRAY]: "bytes11[]",
  [ContractSchemaType.BYTES12_ARRAY]: "bytes12[]",
  [ContractSchemaType.BYTES13_ARRAY]: "bytes13[]",
  [ContractSchemaType.BYTES14_ARRAY]: "bytes14[]",
  [ContractSchemaType.BYTES15_ARRAY]: "bytes15[]",
  [ContractSchemaType.BYTES16_ARRAY]: "bytes16[]",
  [ContractSchemaType.BYTES17_ARRAY]: "bytes17[]",
  [ContractSchemaType.BYTES18_ARRAY]: "bytes18[]",
  [ContractSchemaType.BYTES19_ARRAY]: "bytes19[]",
  [ContractSchemaType.BYTES20_ARRAY]: "bytes20[]",
  [ContractSchemaType.BYTES21_ARRAY]: "bytes21[]",
  [ContractSchemaType.BYTES22_ARRAY]: "bytes22[]",
  [ContractSchemaType.BYTES23_ARRAY]: "bytes23[]",
  [ContractSchemaType.BYTES24_ARRAY]: "bytes24[]",
  [ContractSchemaType.BYTES25_ARRAY]: "bytes25[]",
  [ContractSchemaType.BYTES26_ARRAY]: "bytes26[]",
  [ContractSchemaType.BYTES27_ARRAY]: "bytes27[]",
  [ContractSchemaType.BYTES28_ARRAY]: "bytes28[]",
  [ContractSchemaType.BYTES29_ARRAY]: "bytes29[]",
  [ContractSchemaType.BYTES30_ARRAY]: "bytes30[]",
  [ContractSchemaType.BYTES31_ARRAY]: "bytes31[]",
  [ContractSchemaType.BYTES32_ARRAY]: "bytes32[]",

  [ContractSchemaType.BOOL_ARRAY]: "bool[]",
  [ContractSchemaType.ADDRESS_ARRAY]: "address[]",

  [ContractSchemaType.BYTES]: "bytes",
  [ContractSchemaType.STRING]: "string",
};

export const ContractSchemaTypeArrayToElement = {
  [ContractSchemaType.UINT8_ARRAY]: ContractSchemaType.UINT8,
  [ContractSchemaType.UINT16_ARRAY]: ContractSchemaType.UINT16,
  [ContractSchemaType.UINT24_ARRAY]: ContractSchemaType.UINT24,
  [ContractSchemaType.UINT32_ARRAY]: ContractSchemaType.UINT32,
  [ContractSchemaType.UINT40_ARRAY]: ContractSchemaType.UINT40,
  [ContractSchemaType.UINT48_ARRAY]: ContractSchemaType.UINT48,
  [ContractSchemaType.UINT56_ARRAY]: ContractSchemaType.UINT56,
  [ContractSchemaType.UINT64_ARRAY]: ContractSchemaType.UINT64,
  [ContractSchemaType.UINT72_ARRAY]: ContractSchemaType.UINT72,
  [ContractSchemaType.UINT80_ARRAY]: ContractSchemaType.UINT80,
  [ContractSchemaType.UINT88_ARRAY]: ContractSchemaType.UINT88,
  [ContractSchemaType.UINT96_ARRAY]: ContractSchemaType.UINT96,
  [ContractSchemaType.UINT104_ARRAY]: ContractSchemaType.UINT104,
  [ContractSchemaType.UINT112_ARRAY]: ContractSchemaType.UINT112,
  [ContractSchemaType.UINT120_ARRAY]: ContractSchemaType.UINT120,
  [ContractSchemaType.UINT128_ARRAY]: ContractSchemaType.UINT128,
  [ContractSchemaType.UINT136_ARRAY]: ContractSchemaType.UINT136,
  [ContractSchemaType.UINT144_ARRAY]: ContractSchemaType.UINT144,
  [ContractSchemaType.UINT152_ARRAY]: ContractSchemaType.UINT152,
  [ContractSchemaType.UINT160_ARRAY]: ContractSchemaType.UINT160,
  [ContractSchemaType.UINT168_ARRAY]: ContractSchemaType.UINT168,
  [ContractSchemaType.UINT176_ARRAY]: ContractSchemaType.UINT176,
  [ContractSchemaType.UINT184_ARRAY]: ContractSchemaType.UINT184,
  [ContractSchemaType.UINT192_ARRAY]: ContractSchemaType.UINT192,
  [ContractSchemaType.UINT200_ARRAY]: ContractSchemaType.UINT200,
  [ContractSchemaType.UINT208_ARRAY]: ContractSchemaType.UINT208,
  [ContractSchemaType.UINT216_ARRAY]: ContractSchemaType.UINT216,
  [ContractSchemaType.UINT224_ARRAY]: ContractSchemaType.UINT224,
  [ContractSchemaType.UINT232_ARRAY]: ContractSchemaType.UINT232,
  [ContractSchemaType.UINT240_ARRAY]: ContractSchemaType.UINT240,
  [ContractSchemaType.UINT248_ARRAY]: ContractSchemaType.UINT248,
  [ContractSchemaType.UINT256_ARRAY]: ContractSchemaType.UINT256,

  [ContractSchemaType.INT8_ARRAY]: ContractSchemaType.INT8,
  [ContractSchemaType.INT16_ARRAY]: ContractSchemaType.INT16,
  [ContractSchemaType.INT24_ARRAY]: ContractSchemaType.INT24,
  [ContractSchemaType.INT32_ARRAY]: ContractSchemaType.INT32,
  [ContractSchemaType.INT40_ARRAY]: ContractSchemaType.INT40,
  [ContractSchemaType.INT48_ARRAY]: ContractSchemaType.INT48,
  [ContractSchemaType.INT56_ARRAY]: ContractSchemaType.INT56,
  [ContractSchemaType.INT64_ARRAY]: ContractSchemaType.INT64,
  [ContractSchemaType.INT72_ARRAY]: ContractSchemaType.INT72,
  [ContractSchemaType.INT80_ARRAY]: ContractSchemaType.INT80,
  [ContractSchemaType.INT88_ARRAY]: ContractSchemaType.INT88,
  [ContractSchemaType.INT96_ARRAY]: ContractSchemaType.INT96,
  [ContractSchemaType.INT104_ARRAY]: ContractSchemaType.INT104,
  [ContractSchemaType.INT112_ARRAY]: ContractSchemaType.INT112,
  [ContractSchemaType.INT120_ARRAY]: ContractSchemaType.INT120,
  [ContractSchemaType.INT128_ARRAY]: ContractSchemaType.INT128,
  [ContractSchemaType.INT136_ARRAY]: ContractSchemaType.INT136,
  [ContractSchemaType.INT144_ARRAY]: ContractSchemaType.INT144,
  [ContractSchemaType.INT152_ARRAY]: ContractSchemaType.INT152,
  [ContractSchemaType.INT160_ARRAY]: ContractSchemaType.INT160,
  [ContractSchemaType.INT168_ARRAY]: ContractSchemaType.INT168,
  [ContractSchemaType.INT176_ARRAY]: ContractSchemaType.INT176,
  [ContractSchemaType.INT184_ARRAY]: ContractSchemaType.INT184,
  [ContractSchemaType.INT192_ARRAY]: ContractSchemaType.INT192,
  [ContractSchemaType.INT200_ARRAY]: ContractSchemaType.INT200,
  [ContractSchemaType.INT208_ARRAY]: ContractSchemaType.INT208,
  [ContractSchemaType.INT216_ARRAY]: ContractSchemaType.INT216,
  [ContractSchemaType.INT224_ARRAY]: ContractSchemaType.INT224,
  [ContractSchemaType.INT232_ARRAY]: ContractSchemaType.INT232,
  [ContractSchemaType.INT240_ARRAY]: ContractSchemaType.INT240,
  [ContractSchemaType.INT248_ARRAY]: ContractSchemaType.INT248,
  [ContractSchemaType.INT256_ARRAY]: ContractSchemaType.INT256,

  [ContractSchemaType.BYTES1_ARRAY]: ContractSchemaType.BYTES1,
  [ContractSchemaType.BYTES2_ARRAY]: ContractSchemaType.BYTES2,
  [ContractSchemaType.BYTES3_ARRAY]: ContractSchemaType.BYTES3,
  [ContractSchemaType.BYTES4_ARRAY]: ContractSchemaType.BYTES4,
  [ContractSchemaType.BYTES5_ARRAY]: ContractSchemaType.BYTES5,
  [ContractSchemaType.BYTES6_ARRAY]: ContractSchemaType.BYTES6,
  [ContractSchemaType.BYTES7_ARRAY]: ContractSchemaType.BYTES7,
  [ContractSchemaType.BYTES8_ARRAY]: ContractSchemaType.BYTES8,
  [ContractSchemaType.BYTES9_ARRAY]: ContractSchemaType.BYTES9,
  [ContractSchemaType.BYTES10_ARRAY]: ContractSchemaType.BYTES10,
  [ContractSchemaType.BYTES11_ARRAY]: ContractSchemaType.BYTES11,
  [ContractSchemaType.BYTES12_ARRAY]: ContractSchemaType.BYTES12,
  [ContractSchemaType.BYTES13_ARRAY]: ContractSchemaType.BYTES13,
  [ContractSchemaType.BYTES14_ARRAY]: ContractSchemaType.BYTES14,
  [ContractSchemaType.BYTES15_ARRAY]: ContractSchemaType.BYTES15,
  [ContractSchemaType.BYTES16_ARRAY]: ContractSchemaType.BYTES16,
  [ContractSchemaType.BYTES17_ARRAY]: ContractSchemaType.BYTES17,
  [ContractSchemaType.BYTES18_ARRAY]: ContractSchemaType.BYTES18,
  [ContractSchemaType.BYTES19_ARRAY]: ContractSchemaType.BYTES19,
  [ContractSchemaType.BYTES20_ARRAY]: ContractSchemaType.BYTES20,
  [ContractSchemaType.BYTES21_ARRAY]: ContractSchemaType.BYTES21,
  [ContractSchemaType.BYTES22_ARRAY]: ContractSchemaType.BYTES22,
  [ContractSchemaType.BYTES23_ARRAY]: ContractSchemaType.BYTES23,
  [ContractSchemaType.BYTES24_ARRAY]: ContractSchemaType.BYTES24,
  [ContractSchemaType.BYTES25_ARRAY]: ContractSchemaType.BYTES25,
  [ContractSchemaType.BYTES26_ARRAY]: ContractSchemaType.BYTES26,
  [ContractSchemaType.BYTES27_ARRAY]: ContractSchemaType.BYTES27,
  [ContractSchemaType.BYTES28_ARRAY]: ContractSchemaType.BYTES28,
  [ContractSchemaType.BYTES29_ARRAY]: ContractSchemaType.BYTES29,
  [ContractSchemaType.BYTES30_ARRAY]: ContractSchemaType.BYTES30,
  [ContractSchemaType.BYTES31_ARRAY]: ContractSchemaType.BYTES31,
  [ContractSchemaType.BYTES32_ARRAY]: ContractSchemaType.BYTES32,

  [ContractSchemaType.BOOL_ARRAY]: ContractSchemaType.BOOL,
  [ContractSchemaType.ADDRESS_ARRAY]: ContractSchemaType.ADDRESS,
} as { [key in ContractSchemaType]?: ContractSchemaType };
