// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import { console } from "forge-std/console.sol";
import { IStore } from "store/IStore.sol";
import { SchemaType } from "store/Types.sol";
import { Schema } from "store/Schema.sol";
import { SystemSchemaLib as SchemaLib } from "../schemas/System.sol";

// -- User defined schema and tableId --
bytes32 constant tableId = keccak256("mud.world.table.system");

// -- Autogenerated library to interact with tables with this schema --
// TODO: autogenerate

library SystemTable {
  /** Register the table's schema */
  function registerSchema() internal {
    SchemaLib.registerSchema(tableId);
  }

  function registerSchema(IStore store) internal {
    SchemaLib.registerSchema(tableId, store);
  }

  /** Set the table's data */
  function set(
    bytes32 routeId,
    address system,
    bool publicAccess
  ) internal {
    SchemaLib.set(tableId, routeId, system, publicAccess);
  }

  /** Get the table's data */
  function get(bytes32 routeId) internal view returns (address, bool) {
    return SchemaLib.get(tableId, routeId);
  }

  function get(IStore store, bytes32 routeId) internal view returns (address, bool) {
    return SchemaLib.get(tableId, store, routeId);
  }
}
