// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import { console } from "forge-std/console.sol";
import { IStore } from "store/IStore.sol";
import { SchemaType } from "store/Types.sol";
import { Schema } from "store/Schema.sol";
import { AddressToBytes32SchemaLib as SchemaLib } from "../schemas/AddressToBytes32.sol";

// -- User defined schema and tableId --
bytes32 constant tableId = keccak256("mud.world.table.systemRoute");

// -- Autogenerated library to interact with tables with this schema --
// TODO: autogenerate

library SystemRouteTable {
  /** Register the table's schema */
  function registerSchema() internal {
    SchemaLib.registerSchema(tableId);
  }

  function registerSchema(IStore store) internal {
    SchemaLib.registerSchema(tableId, store);
  }

  function registerSchemaInternal() internal {
    SchemaLib.registerSchemaInternal(tableId);
  }

  /** Set the table's data */
  function set(address system, bytes32 route) internal {
    SchemaLib.set(tableId, system, route);
  }

  /** Get the table's data */
  function get(address system) internal view returns (bytes32) {
    return SchemaLib.get(tableId, system);
  }

  function get(IStore store, address system) internal view returns (bytes32) {
    return SchemaLib.get(tableId, store, system);
  }
}
