import { describe, it, expect } from "vitest";
import { createSqliteTable } from "./createSqliteTable";

describe("createSqliteTable", () => {
  it.only("should create table from schema", async () => {
    const table = createSqliteTable({
      address: "0xffffffffffffffffffffffffffffffffffffffff",
      namespace: "test",
      name: "users",
      keySchema: { x: "uint32", y: "uint32" },
      valueSchema: { name: "string", addr: "address" },
    });

    console.log("table", table);

    expect(table).toMatchInlineSnapshot(`
      SQLiteTable {
        "__isDeleted": SQLiteBoolean {
          "autoIncrement": false,
          "config": {
            "autoIncrement": false,
            "default": undefined,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "mode": "boolean",
          "name": "__isDeleted",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "__key": SQLiteText {
          "config": {
            "default": undefined,
            "enumValues": [],
            "length": undefined,
            "name": "__key",
            "notNull": true,
            "primaryKey": true,
          },
          "default": undefined,
          "enumValues": [],
          "hasDefault": undefined,
          "length": undefined,
          "name": "__key",
          "notNull": true,
          "primary": true,
          "table": [Circular],
        },
        "__lastUpdatedBlockNumber": SQLiteBigInt {
          "config": {
            "default": undefined,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "name": "__lastUpdatedBlockNumber",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "addr": SQLiteCustomColumn {
          "config": {
            "customTypeParams": {
              "dataType": [Function],
              "fromDriver": [Function],
              "toDriver": [Function],
            },
            "default": undefined,
            "fieldConfig": undefined,
            "name": "addr",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "mapFrom": [Function],
          "mapTo": [Function],
          "name": "addr",
          "notNull": true,
          "primary": false,
          "sqlName": "text",
          "table": [Circular],
        },
        "name": SQLiteText {
          "config": {
            "default": undefined,
            "enumValues": [],
            "length": undefined,
            "name": "name",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "enumValues": [],
          "hasDefault": undefined,
          "length": undefined,
          "name": "name",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "x": SQLiteInteger {
          "autoIncrement": false,
          "config": {
            "autoIncrement": false,
            "default": undefined,
            "name": "x",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "name": "x",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "y": SQLiteInteger {
          "autoIncrement": false,
          "config": {
            "autoIncrement": false,
            "default": undefined,
            "name": "y",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "name": "y",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        Symbol(drizzle:Name): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:OriginalName): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:Schema): undefined,
        Symbol(drizzle:Columns): {
          "__isDeleted": SQLiteBoolean {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": undefined,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "__key": SQLiteText {
            "config": {
              "default": undefined,
              "enumValues": [],
              "length": undefined,
              "name": "__key",
              "notNull": true,
              "primaryKey": true,
            },
            "default": undefined,
            "enumValues": [],
            "hasDefault": undefined,
            "length": undefined,
            "name": "__key",
            "notNull": true,
            "primary": true,
            "table": [Circular],
          },
          "__lastUpdatedBlockNumber": SQLiteBigInt {
            "config": {
              "default": undefined,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "addr": SQLiteCustomColumn {
            "config": {
              "customTypeParams": {
                "dataType": [Function],
                "fromDriver": [Function],
                "toDriver": [Function],
              },
              "default": undefined,
              "fieldConfig": undefined,
              "name": "addr",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "mapFrom": [Function],
            "mapTo": [Function],
            "name": "addr",
            "notNull": true,
            "primary": false,
            "sqlName": "text",
            "table": [Circular],
          },
          "name": SQLiteText {
            "config": {
              "default": undefined,
              "enumValues": [],
              "length": undefined,
              "name": "name",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "enumValues": [],
            "hasDefault": undefined,
            "length": undefined,
            "name": "name",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "x": SQLiteInteger {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": undefined,
              "name": "x",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "name": "x",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "y": SQLiteInteger {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": undefined,
              "name": "y",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "name": "y",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
        },
        Symbol(drizzle:BaseName): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:IsAlias): false,
        Symbol(drizzle:ExtraConfigBuilder): undefined,
        Symbol(drizzle:IsDrizzleTable): true,
        Symbol(drizzle:SQLiteInlineForeignKeys): [],
      }
    `);
  });

  it("can create a singleton table", async () => {
    const table = createSqliteTable({
      address: "0xffffffffffffffffffffffffffffffffffffffff",
      namespace: "test",
      name: "users",
      keySchema: {},
      valueSchema: { addrs: "address[]" },
    });

    expect(table).toMatchInlineSnapshot(`
      SQLiteTable {
        "__isDeleted": SQLiteBoolean {
          "autoIncrement": false,
          "config": {
            "autoIncrement": false,
            "default": undefined,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "mode": "boolean",
          "name": "__isDeleted",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "__key": SQLiteText {
          "config": {
            "default": undefined,
            "enumValues": [],
            "length": undefined,
            "name": "__key",
            "notNull": true,
            "primaryKey": true,
          },
          "default": undefined,
          "enumValues": [],
          "hasDefault": undefined,
          "length": undefined,
          "name": "__key",
          "notNull": true,
          "primary": true,
          "table": [Circular],
        },
        "__lastUpdatedBlockNumber": SQLiteBigInt {
          "config": {
            "default": undefined,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "name": "__lastUpdatedBlockNumber",
          "notNull": true,
          "primary": false,
          "table": [Circular],
        },
        "addrs": SQLiteCustomColumn {
          "config": {
            "customTypeParams": {
              "dataType": [Function],
              "fromDriver": [Function],
              "toDriver": [Function],
            },
            "default": undefined,
            "fieldConfig": undefined,
            "name": "addrs",
            "notNull": true,
            "primaryKey": false,
          },
          "default": undefined,
          "hasDefault": undefined,
          "mapFrom": [Function],
          "mapTo": [Function],
          "name": "addrs",
          "notNull": true,
          "primary": false,
          "sqlName": "text",
          "table": [Circular],
        },
        Symbol(drizzle:Name): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:OriginalName): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:Schema): undefined,
        Symbol(drizzle:Columns): {
          "__isDeleted": SQLiteBoolean {
            "autoIncrement": false,
            "config": {
              "autoIncrement": false,
              "default": undefined,
              "mode": "boolean",
              "name": "__isDeleted",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "mode": "boolean",
            "name": "__isDeleted",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "__key": SQLiteText {
            "config": {
              "default": undefined,
              "enumValues": [],
              "length": undefined,
              "name": "__key",
              "notNull": true,
              "primaryKey": true,
            },
            "default": undefined,
            "enumValues": [],
            "hasDefault": undefined,
            "length": undefined,
            "name": "__key",
            "notNull": true,
            "primary": true,
            "table": [Circular],
          },
          "__lastUpdatedBlockNumber": SQLiteBigInt {
            "config": {
              "default": undefined,
              "name": "__lastUpdatedBlockNumber",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "name": "__lastUpdatedBlockNumber",
            "notNull": true,
            "primary": false,
            "table": [Circular],
          },
          "addrs": SQLiteCustomColumn {
            "config": {
              "customTypeParams": {
                "dataType": [Function],
                "fromDriver": [Function],
                "toDriver": [Function],
              },
              "default": undefined,
              "fieldConfig": undefined,
              "name": "addrs",
              "notNull": true,
              "primaryKey": false,
            },
            "default": undefined,
            "hasDefault": undefined,
            "mapFrom": [Function],
            "mapTo": [Function],
            "name": "addrs",
            "notNull": true,
            "primary": false,
            "sqlName": "text",
            "table": [Circular],
          },
        },
        Symbol(drizzle:BaseName): "0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF__test__users",
        Symbol(drizzle:IsAlias): false,
        Symbol(drizzle:ExtraConfigBuilder): undefined,
        Symbol(drizzle:IsDrizzleTable): true,
        Symbol(drizzle:SQLiteInlineForeignKeys): [],
      }
    `);
  });
});
