// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.3
// source: proto/mode.proto

package mode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QueryLayer_GetState_FullMethodName           = "/mode.QueryLayer/GetState"
	QueryLayer_StreamState_FullMethodName        = "/mode.QueryLayer/StreamState"
	QueryLayer_GetPartialState_FullMethodName    = "/mode.QueryLayer/GetPartialState"
	QueryLayer_StreamPartialState_FullMethodName = "/mode.QueryLayer/StreamPartialState"
)

// QueryLayerClient is the client API for QueryLayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryLayerClient interface {
	// Get entire state.
	GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*QueryLayerStateResponse, error)
	// Stream entire state.
	StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (QueryLayer_StreamStateClient, error)
	// Get state for a single table.
	GetPartialState(ctx context.Context, in *PartialStateRequest, opts ...grpc.CallOption) (*QueryLayerStateResponse, error)
	// Stream state for a single table.
	StreamPartialState(ctx context.Context, in *PartialStateRequest, opts ...grpc.CallOption) (QueryLayer_StreamPartialStateClient, error)
}

type queryLayerClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryLayerClient(cc grpc.ClientConnInterface) QueryLayerClient {
	return &queryLayerClient{cc}
}

func (c *queryLayerClient) GetState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*QueryLayerStateResponse, error) {
	out := new(QueryLayerStateResponse)
	err := c.cc.Invoke(ctx, QueryLayer_GetState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryLayerClient) StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (QueryLayer_StreamStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &QueryLayer_ServiceDesc.Streams[0], QueryLayer_StreamState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queryLayerStreamStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryLayer_StreamStateClient interface {
	Recv() (*QueryLayerStateStreamResponse, error)
	grpc.ClientStream
}

type queryLayerStreamStateClient struct {
	grpc.ClientStream
}

func (x *queryLayerStreamStateClient) Recv() (*QueryLayerStateStreamResponse, error) {
	m := new(QueryLayerStateStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryLayerClient) GetPartialState(ctx context.Context, in *PartialStateRequest, opts ...grpc.CallOption) (*QueryLayerStateResponse, error) {
	out := new(QueryLayerStateResponse)
	err := c.cc.Invoke(ctx, QueryLayer_GetPartialState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryLayerClient) StreamPartialState(ctx context.Context, in *PartialStateRequest, opts ...grpc.CallOption) (QueryLayer_StreamPartialStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &QueryLayer_ServiceDesc.Streams[1], QueryLayer_StreamPartialState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queryLayerStreamPartialStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryLayer_StreamPartialStateClient interface {
	Recv() (*QueryLayerStateStreamResponse, error)
	grpc.ClientStream
}

type queryLayerStreamPartialStateClient struct {
	grpc.ClientStream
}

func (x *queryLayerStreamPartialStateClient) Recv() (*QueryLayerStateStreamResponse, error) {
	m := new(QueryLayerStateStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueryLayerServer is the server API for QueryLayer service.
// All implementations must embed UnimplementedQueryLayerServer
// for forward compatibility
type QueryLayerServer interface {
	// Get entire state.
	GetState(context.Context, *StateRequest) (*QueryLayerStateResponse, error)
	// Stream entire state.
	StreamState(*StateRequest, QueryLayer_StreamStateServer) error
	// Get state for a single table.
	GetPartialState(context.Context, *PartialStateRequest) (*QueryLayerStateResponse, error)
	// Stream state for a single table.
	StreamPartialState(*PartialStateRequest, QueryLayer_StreamPartialStateServer) error
	mustEmbedUnimplementedQueryLayerServer()
}

// UnimplementedQueryLayerServer must be embedded to have forward compatible implementations.
type UnimplementedQueryLayerServer struct {
}

func (UnimplementedQueryLayerServer) GetState(context.Context, *StateRequest) (*QueryLayerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedQueryLayerServer) StreamState(*StateRequest, QueryLayer_StreamStateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedQueryLayerServer) GetPartialState(context.Context, *PartialStateRequest) (*QueryLayerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartialState not implemented")
}
func (UnimplementedQueryLayerServer) StreamPartialState(*PartialStateRequest, QueryLayer_StreamPartialStateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPartialState not implemented")
}
func (UnimplementedQueryLayerServer) mustEmbedUnimplementedQueryLayerServer() {}

// UnsafeQueryLayerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryLayerServer will
// result in compilation errors.
type UnsafeQueryLayerServer interface {
	mustEmbedUnimplementedQueryLayerServer()
}

func RegisterQueryLayerServer(s grpc.ServiceRegistrar, srv QueryLayerServer) {
	s.RegisterService(&QueryLayer_ServiceDesc, srv)
}

func _QueryLayer_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryLayerServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryLayer_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryLayerServer).GetState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryLayer_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryLayerServer).StreamState(m, &queryLayerStreamStateServer{stream})
}

type QueryLayer_StreamStateServer interface {
	Send(*QueryLayerStateStreamResponse) error
	grpc.ServerStream
}

type queryLayerStreamStateServer struct {
	grpc.ServerStream
}

func (x *queryLayerStreamStateServer) Send(m *QueryLayerStateStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _QueryLayer_GetPartialState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartialStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryLayerServer).GetPartialState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryLayer_GetPartialState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryLayerServer).GetPartialState(ctx, req.(*PartialStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryLayer_StreamPartialState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PartialStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryLayerServer).StreamPartialState(m, &queryLayerStreamPartialStateServer{stream})
}

type QueryLayer_StreamPartialStateServer interface {
	Send(*QueryLayerStateStreamResponse) error
	grpc.ServerStream
}

type queryLayerStreamPartialStateServer struct {
	grpc.ServerStream
}

func (x *queryLayerStreamPartialStateServer) Send(m *QueryLayerStateStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// QueryLayer_ServiceDesc is the grpc.ServiceDesc for QueryLayer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryLayer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mode.QueryLayer",
	HandlerType: (*QueryLayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _QueryLayer_GetState_Handler,
		},
		{
			MethodName: "GetPartialState",
			Handler:    _QueryLayer_GetPartialState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _QueryLayer_StreamState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPartialState",
			Handler:       _QueryLayer_StreamPartialState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mode.proto",
}
