name: Integration sandbox

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Build/test integration sandbox
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/latticexyz/postgres-wal-logical:latest
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: mode_ephemeral
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Install integration sandbox dependencies
        working-directory: ./integration-sandbox
        run: pnpm install

      - name: Install Playwright Dependencies
        run: pnpx playwright install --with-deps chromium

      - name: Clean integration sandbox
        working-directory: ./integration-sandbox
        run: pnpm run clean

      - name: Build integration sandbox
        working-directory: ./integration-sandbox
        run: pnpm run build

      - name: Outdated files, run `pnpm run build` in `integration-sandbox` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Run tests
        working-directory: ./integration-sandbox/packages/test
        run: pnpm test
