name: Version 🔖

on:
  push:
    branches:
      - v2

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Release
    if: github.repository == 'latticexyz/mud'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Clean
        shell: bash
        run: pnpm turbo run clean --force --concurrency 10

      # Build without cache to ensure we release with the most accurate output
      - name: Build
        shell: bash
        run: pnpm turbo run build --force --concurrency 10

      - name: Outdated files, run `pnpm build` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".changeset/pre.json"

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      # https://github.com/changesets/action#with-publishing
      - name: Handle Release Pull Request or Publish to npm
        id: changesets
        if: steps.check_files.outputs.files_exists == 'false'
        uses: changesets/action@v1
        with:
          title: "chore: version packages 🔖"
          commit: "chore: version packages 🔖"
          publish: pnpm release:publish
          version: pnpm release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docker:
    uses: ./.github/workflows/docker.yml
    needs: version
