name: Remove npm tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name in npm"
        type: string
        required: true

jobs:
  remove-npm-tag:
    name: Remove an npm dist tag for the current branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Remove npm dist tag
        run: pnpm run dist-tag-rm
        env:
          TAG: ${{ github.event.inputs.tag }}
