name: Test published packages

on:
  workflow_call:
    inputs:
      tag-or-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag-or-version:
        required: true
        type: string
        description: npm tag or version of MUD

jobs:
  test-create-mud-project:
    name: Test create-mud project
    strategy:
      matrix:
        os: [depot-ubuntu-22.04-16]
        template: [vanilla, react, react-ecs, phaser, threejs]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .github

      - name: Setup
        uses: ./.github/actions/setup-prerequisites

      - name: Test
        run: |
          pnpm create mud@${{ inputs.tag-or-version }} --name project --template ${{ matrix.template }}
          pnpm --dir project install
          pnpm --dir project run test
